AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3.3
  NewCops: enable
  SuggestExtensions: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 30
